"""
Django settings for sitioWeb project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from telnetlib import LOGOUT
from django.urls import reverse_lazy


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_)@uu(0a3&s)#p$jhbhwukcx$g47+gn@998^7v=^j-88x97568'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    'apps.pagina',
    'apps.plataforma',
    ##Libreria allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    #Se agregan los que se necesiten, en este caso vamos a iniciar sesión con google (ver documentacion del allauth/installacion)
    'allauth.socialaccount.providers.google',
    #formularios django
    'crispy_forms',
    #captcha :p
    'captcha',
    #pwa
    'pwa',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sitioWeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'apps/pagina/templates/pagina', BASE_DIR / 'apps/plataforma/templates/plataforma',
        BASE_DIR / 'apps/pagina/templates/pagina/account'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sitioWeb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'rokfgyns',
        'USER' : 'rokfgyns',
        'PASSWORD': 'vc4w8oUKXuP1rcPdtxg-RdGEmPg8c52a',
        'HOST': 'fanny.db.elephantsql.com',
        'DATABASE_PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTH_USER_MODEL = 'plataforma.Usuario'

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'es-COL'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

LOGIN_REDIRECT_URL = '../../../../home/'
LOGOUT_REDIRECT_URL = '../../index.html'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#correos
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "paginapuerchag@gmail.com"
EMAIL_HOST_PASSWORD = "ozklgkbtajoukpcl"

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

#el método de autenticacion para iniciar sesion es email. No el nombre de usuario
ACCOUNT_AUTHENTICATION_METHOD = 'email' 
#es obligación tener un email para ingresar
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_UNIQUE = True
#tiene que verificar manualmente el correo electronico que se registra
ACCOUNT_EMAIL_VERIFICATION = True  
#tiene un plazo de una semana para hacerlo
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 7  

#claves captcha api google
RECAPTCHA_PUBLIC_KEY = '6LfuXgkhAAAAAMT7lzAO9jObbhgKnHDi0tACvgga'
GOOGLE_RECAPTCHA_PRIVATE_KEY = '6LfuXgkhAAAAAJbTiuQXc9EQuVzijYG_eGE0cBGy'
RECAPTCHA_REQUIRED_SCORE = 0.85
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']

#manifesto
PWA_APP_NAME = 'Plataforma Sede Educativa Puerchag'
PWA_APP_SHORT_NAME = 'SE Puerchag'
PWA_APP_START_URL = '/index'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_BACKGROUND_COLOR = '#F7F7F7'
PWA_APP_THEME_COLOR = '#46c34a'
PWA_APP_ORIENTATION = 'portrait-primary'
PWA_APP_ICONS = [
        {'src': '/static/img/core-img/titulo.png',
        'type': 'image/png',
        'sizes': '230x43'},
        {'src': '/static/img/core-img/titulo144.png',
        'type': 'image/png',
        'sizes': '170x170'}
    ]
PWA_APP_LANG= "es"


MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
