# Generated by Django 3.1.3 on 2022-08-02 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefono_profesor', models.CharField(blank=True, max_length=15, null=True)),
                ('es_profesor', models.BooleanField(default=False)),
                ('es_acudiente', models.BooleanField(default=False)),
                ('es_administrador', models.BooleanField(default=False)),
                ('vigencia', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('periodo_electivo', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('vigencia', models.BooleanField(default=True)),
                ('id_acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.acudiente')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('detalle', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id_sugerencia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_sugerencia', models.DateField()),
                ('detalle_sugerencia', models.TextField(max_length=255)),
                ('id_acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.acudiente')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.BigIntegerField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('periodo', models.CharField(max_length=6)),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=40, null=True)),
                ('comentario', models.TextField(blank=True, max_length=255, null=True)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.asignatura')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='id_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.profesor'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.acudiente')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.curso'),
        ),
    ]
