# Generated by Django 4.1 on 2022-08-05 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_cita', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('profesor_acepto', models.BooleanField(default=False)),
                ('acudiente_acepto', models.BooleanField(default=False)),
                ('id_acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identAcudiente', to=settings.AUTH_USER_MODEL)),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identProfesor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
