# Generated by Django 3.1.3 on 2022-07-10 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0002_auto_20220710_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id_acudiente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('vigencia', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('periodo_electivo', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id_escuela', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono_escuela', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('vigencia', models.BooleanField(default=True)),
                ('id_acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.acudiente')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('sexo_profesor', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('email_profesor', models.EmailField(max_length=254)),
                ('telefono_profesor', models.CharField(max_length=15)),
                ('cargo', models.CharField(choices=[('Profesor', 'Profesor'), ('Rector', 'Rector'), ('Administrador', 'Administrador')], default='Profesor', max_length=20)),
                ('nivel_estudios', models.CharField(choices=[('Tecnico', 'Tecnico'), ('Licenciatura', 'Licenciatura'), ('Pregrado', 'Pregrado'), ('Maestria', 'Maestria'), ('Doctorado', 'Doctorado')], default='Licenciatura', max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('vigencia', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id_sugerencia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_sugerencia', models.DateField()),
                ('detalle_sugerencia', models.TextField()),
                ('id_acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.acudiente')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.BigIntegerField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('periodo', models.CharField(max_length=6)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('Parcial', 'Parcial'), ('Quiz', 'Quiz'), ('Tarea', 'Tarea'), ('Trabajo', 'Trabajo')], default='Tarea', max_length=20)),
                ('comentario', models.TextField()),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.asignatura')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('detalle', models.TextField()),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='id_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.profesor'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.acudiente')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.curso'),
        ),
    ]
