# Generated by Django 3.1.3 on 2022-08-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_auto_20220710_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='id_nota',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
