# Generated by Django 3.1.3 on 2022-08-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_auto_20220801_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='id_nota',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
